## 1. Importing Required Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 2. Data Visualization

In [2]:
ipl = pd.read_csv('datasets_matches.csv')

In [3]:
# shape of data frame
ipl.shape

(636, 18)

In [4]:
# checking data frame
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,05-04-17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,06-04-17,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,07-04-17,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,08-04-17,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,08-04-17,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [5]:
# all attributes in dataframe
ipl.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [6]:
# datatype of all attributes
ipl.dtypes

id                   int64
season               int64
city                object
date                object
team1               object
team2               object
toss_winner         object
toss_decision       object
result              object
dl_applied           int64
winner              object
win_by_runs          int64
win_by_wickets       int64
player_of_match     object
venue               object
umpire1             object
umpire2             object
umpire3            float64
dtype: object

## 3. Data Manipulation

In [7]:
# checking missing data in any column
ipl.isna().any()

id                 False
season             False
city                True
date               False
team1              False
team2              False
toss_winner        False
toss_decision      False
result             False
dl_applied         False
winner              True
win_by_runs        False
win_by_wickets     False
player_of_match     True
venue              False
umpire1             True
umpire2             True
umpire3             True
dtype: bool

In [8]:
# umpire 3 is completely empty so removing it
ipl.drop(['umpire3'], axis = 1, inplace=True)
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,Hyderabad,05-04-17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,Pune,06-04-17,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi
2,3,2017,Rajkot,07-04-17,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan
3,4,2017,Indore,08-04-17,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin
4,5,2017,Bangalore,08-04-17,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN

In [9]:
ipl.dropna(inplace=True)
ipl.shape

(625, 17)

### Total matches won by teams

In [10]:
team = ipl['winner'].value_counts(sort=False).index.tolist()
wins = ipl['winner'].value_counts(sort=False).tolist()
ipl_new = pd.DataFrame({
    'Team': team,
    'Total_Wins': wins
})
ipl_new

                           Team  Total_Wins
0              Delhi Daredevils          61
1           Sunrisers Hyderabad          40
2                 Pune Warriors          12
3           Chennai Super Kings          77
4                Mumbai Indians          92
5          Kochi Tuskers Kerala           6
6               Kings XI Punjab          69
7       Rising Pune Supergiants           5
8         Kolkata Knight Riders          77
9        Rising Pune Supergiant          10
10             Rajasthan Royals          63
11              Deccan Chargers          29
12  Royal Challengers Bangalore          71
13                Gujarat Lions          13

In [11]:
team1 = ipl['team1'].value_counts(sort=False).tolist()
team1

[61, 44, 20, 76, 80, 7, 77, 7, 67, 8, 54, 43, 67, 14]

In [12]:
team2 = ipl['team2'].value_counts(sort=False).tolist()
team2

[81, 70, 25, 53, 74, 30, 7, 7, 80, 8, 62, 32, 80, 16]

### Total Matches Played

In [14]:
total_team = []
for i in range(len(team1)):
    total_team.append(team1[i] + team2[i])
total_team

[142, 114, 45, 129, 154, 37, 84, 14, 147, 16, 116, 75, 147, 30]

In [15]:
ipl_new['Total_Matches'] = total_team
ipl_new

                           Team  Total_Wins  Total_Matches
0              Delhi Daredevils          61            142
1           Sunrisers Hyderabad          40            114
2                 Pune Warriors          12             45
3           Chennai Super Kings          77            129
4                Mumbai Indians          92            154
5          Kochi Tuskers Kerala           6             37
6               Kings XI Punjab          69             84
7       Rising Pune Supergiants           5             14
8         Kolkata Knight Riders          77            147
9        Rising Pune Supergiant          10             16
10             Rajasthan Royals          63            116
11              Deccan Chargers          29             75
12  Royal Challengers Bangalore          71            147
13                Gujarat Lions          13             30

### Win Percentage

In [16]:
ipl_new['Win_Percentage'] = (ipl_new['Total_Wins'] / ipl_new['Total_Matches']) * 100
ipl_new

                           Team  Total_Wins  Total_Matches  Win_Percentage
0              Delhi Daredevils          61            142       42.957746
1           Sunrisers Hyderabad          40            114       35.087719
2                 Pune Warriors          12             45       26.666667
3           Chennai Super Kings          77            129       59.689922
4                Mumbai Indians          92            154       59.740260
5          Kochi Tuskers Kerala           6             37       16.216216
6               Kings XI Punjab          69             84       82.142857
7       Rising Pune Supergiants           5             14       35.714286
8         Kolkata Knight Riders          77            147       52.380952
9        Rising Pune Supergiant          10             16       62.500000
10             Rajasthan Royals          63            116       54.310345
11              Deccan Chargers          29             75       38.666667
12  Royal Challengers Bangalore          71            147       48.299320
13                Gujarat Lions          13             30       43.333333

In [17]:
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,Hyderabad,05-04-17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,Pune,06-04-17,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi
2,3,2017,Rajkot,07-04-17,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan
3,4,2017,Indore,08-04-17,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin
5,6,2017,Hyderabad,09-04-17,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong

### Win When Bat First V/s Field First

In [18]:
ipl.groupby('winner').toss_decision.nunique()

winner
Chennai Super Kings            2
Deccan Chargers                2
Delhi Daredevils               2
Gujarat Lions                  2
Kings XI Punjab                2
Kochi Tuskers Kerala           1
Kolkata Knight Riders          2
Mumbai Indians                 2
Pune Warriors                  2
Rajasthan Royals               2
Rising Pune Supergiant         1
Rising Pune Supergiants        2
Royal Challengers Bangalore    2
Sunrisers Hyderabad            2
Name: toss_decision, dtype: int64

In [19]:
ls = pd.crosstab(ipl['winner'], ipl['toss_decision'])

bat = ls['bat'].tolist()
field = ls['field'].tolist()
ind = ls.index.tolist()

win_by_bat = []
win_by_field = []

for i in range(len(bat)):
    win_by_bat.append((ind[i], bat[i]))
    
for i in range(len(field)):
    win_by_field.append((ind[i], field[i]))
    
win_by_bat, win_by_field

([('Chennai Super Kings', 49),
  ('Deccan Chargers', 14),
  ('Delhi Daredevils', 27),
  ('Gujarat Lions', 2),
  ('Kings XI Punjab', 20),
  ('Kochi Tuskers Kerala', 0),
  ('Kolkata Knight Riders', 34),
  ('Mumbai Indians', 41),
  ('Pune Warriors', 9),
  ('Rajasthan Royals', 30),
  ('Rising Pune Supergiant', 0),
  ('Rising Pune Supergiants', 2),
  ('Royal Challengers Bangalore', 25),
  ('Sunrisers Hyderabad', 15)],
 [('Chennai Super Kings', 28),
  ('Deccan Chargers', 15),
  ('Delhi Daredevils', 34),
  ('Gujarat Lions', 11),
  ('Kings XI Punjab', 49),
  ('Kochi Tuskers Kerala', 6),
  ('Kolkata Knight Riders', 43),
  ('Mumbai Indians', 51),
  ('Pune Warriors', 3),
  ('Rajasthan Royals', 33),
  ('Rising Pune Supergiant', 10),
  ('Rising Pune Supergiants', 3),
  ('Royal Challengers Bangalore', 46),
  ('Sunrisers Hyderabad', 25)])

In [20]:
ls = ipl_new['Team'].tolist()

win_matches_bat = []
win_matches_field = []

for i in ls:
    for j in win_by_bat:
        if i == j[0]:
            win_matches_bat.append(j[1])
for i in ls:
    for j in win_by_field:
        if i == j[0]:
            win_matches_field.append(j[1])
win_matches_bat, win_matches_field

([27, 15, 9, 49, 41, 0, 20, 2, 34, 0, 30, 14, 25, 2],
 [34, 25, 3, 28, 51, 6, 49, 3, 43, 10, 33, 15, 46, 11])

In [21]:
ipl_new['Bat_First_Win'] = win_matches_bat
ipl_new['Field_First_Win'] = win_matches_field
ipl_new

,Team,Total_Wins,Total_Matches,Win_Percentage,Bat_First_Win,Field_First_Win
0,Delhi Daredevils,61,142,42.957746,27,34
1,Sunrisers Hyderabad,40,114,35.087719,15,25
2,Pune Warriors,12,45,26.666667,9,3
3,Chennai Super Kings,77,129,59.689922,49,28
4,Mumbai Indians,92,154,59.740260,41,51
5,Kochi Tuskers Kerala,6,37,16.216216,0,6
6,Kings XI Punjab,69,84,82.142857,20,49
7,Rising Pune Supergiants,5,14,35.714286,2,3
8,Kolkata Knight Riders,77,147,52.380952,34,43
9,Rising Pune Supergiant,10,16,62.500000,0,10
10,Rajasthan Royals,63,116,54.310345,30,33
11,Deccan Chargers,29,75,38.666667,14,15
12,Royal Challengers Bangalore,71,147,48.299320,25,46
13,Gujarat Lions,13,30,43.333333,2,11

In [22]:
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,Hyderabad,05-04-17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,Pune,06-04-17,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi
2,3,2017,Rajkot,07-04-17,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan
3,4,2017,Indore,08-04-17,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin
5,6,2017,Hyderabad,09-04-17,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong

### Favourable Venue

In [23]:
ven = pd.crosstab(ipl['venue'], ipl['winner'])

In [24]:
max_ven = []
for i in ls:
    ven_max = ven[i].argmax()
    max_ven.append(ven_max)
max_ven

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: FutureWarning:
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  This is separate from the ipykernel package so we can avoid doing imports until

['Feroz Shah Kotla',
 'Rajiv Gandhi International Stadium, Uppal',
 'Subrata Roy Sahara Stadium',
 'MA Chidambaram Stadium, Chepauk',
 'Wankhede Stadium',
 'Nehru Stadium',
 'Punjab Cricket Association Stadium, Mohali',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
 'Eden Gardens',
 'Maharashtra Cricket Association Stadium',
 'Sawai Mansingh Stadium',
 'Barabati Stadium',
 'M Chinnaswamy Stadium',
 'Saurashtra Cricket Association Stadium']

In [25]:
ipl_new["Favourable_Venue"] = max_ven
ipl_new

,Team,Total_Wins,Total_Matches,Win_Percentage,Bat_First_Win,Field_First_Win,Favourable_Venue
0,Delhi Daredevils,61,142,42.957746,27,34,Feroz Shah Kotla
1,Sunrisers Hyderabad,40,114,35.087719,15,25,"Rajiv Gandhi International Stadium, Uppal"
2,Pune Warriors,12,45,26.666667,9,3,Subrata Roy Sahara Stadium
3,Chennai Super Kings,77,129,59.689922,49,28,"MA Chidambaram Stadium, Chepauk"
4,Mumbai Indians,92,154,59.740260,41,51,Wankhede Stadium
5,Kochi Tuskers Kerala,6,37,16.216216,0,6,Nehru Stadium
6,Kings XI Punjab,69,84,82.142857,20,49,"Punjab Cricket Association Stadium, Mohali"
7,Rising Pune Supergiants,5,14,35.714286,2,3,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
8,Kolkata Knight Riders,77,147,52.380952,34,43,Eden Gardens
9,Rising Pune Supergiant,10,16,62.500000,0,10,Maharashtra Cricket Association Stadium
10,Rajasthan Royals,63,116,54.310345,30,33,Sawai Mansingh Stadium
11,Deccan Chargers,29,75,38.666667,14,15,Barabati Stadium
12,Royal Challengers Bangalore,71,147,48.299320,25,46,M Chinnaswamy Stadium
13,Gujarat Lions,13,30,43.333333,2,11,Saurashtra Cricket Association Stadium

In [26]:
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,Hyderabad,05-04-17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,Pune,06-04-17,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi
2,3,2017,Rajkot,07-04-17,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan
3,4,2017,Indore,08-04-17,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin
5,6,2017,Hyderabad,09-04-17,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong

### Win Percentage for each Season

In [27]:
season1 = pd.crosstab(ipl['season'], ipl['team1'])
season2 = pd.crosstab(ipl['season'], ipl['team2'])
season2

team2,Chennai Super Kings,Deccan Chargers,Delhi Daredevils,Gujarat Lions,Kings XI Punjab,Kochi Tuskers Kerala,Kolkata Knight Riders,Mumbai Indians,Pune Warriors,Rajasthan Royals,Rising Pune Supergiant,Rising Pune Supergiants,Royal Challengers Bangalore,Sunrisers Hyderabad
season,,,,,,,,,,,,,,
2008,7,6,8,0,8,0,4,8,0,10,0,0,7,0
2009,4,8,8,0,8,0,6,5,0,8,0,0,10,0
2010,8,9,8,0,6,0,6,5,0,6,0,0,12,0
2011,4,5,7,0,7,7,8,8,7,8,0,0,11,0
2012,6,4,14,0,8,0,9,11,9,5,0,0,8,0
2013,10,0,9,0,8,0,9,8,9,10,0,0,5,8
2014,8,0,5,0,6,0,11,5,0,7,0,0,7,4
2015,6,0,7,0,7,0,9,6,0,8,0,0,9,5
2016,0,0,8,10,6,0,8,7,0,0,0,7,6,8
2017,0,0,7,6,6,0,10,11,0,0,8,0,5,5

In [28]:

# Create an empty list 
row_list1 = []
row_list2 = []
# Iterate over each row 
for index, rows in season1.iterrows(): 
    my_list = []
    for j in ls:
        my_list.append(rows[j])
    row_list1.append(my_list)

for index, rows in season2.iterrows(): 
    my_list = []
    for j in ls:
        my_list.append(rows[j])
    row_list2.append(my_list)
row_list2

[[8, 0, 0, 7, 8, 0, 8, 0, 4, 0, 10, 6, 7, 0],
 [8, 0, 0, 4, 5, 0, 8, 0, 6, 0, 8, 8, 10, 0],
 [8, 0, 0, 8, 5, 0, 6, 0, 6, 0, 6, 9, 12, 0],
 [7, 0, 7, 4, 8, 7, 7, 0, 8, 0, 8, 5, 11, 0],
 [14, 0, 9, 6, 11, 0, 8, 0, 9, 0, 5, 4, 8, 0],
 [9, 8, 9, 10, 8, 0, 8, 0, 9, 0, 10, 0, 5, 0],
 [5, 4, 0, 8, 5, 0, 6, 0, 11, 0, 7, 0, 7, 0],
 [7, 5, 0, 6, 6, 0, 7, 0, 9, 0, 8, 0, 9, 0],
 [8, 8, 0, 0, 7, 0, 6, 7, 8, 0, 0, 0, 6, 10],
 [7, 5, 0, 0, 11, 0, 6, 0, 10, 8, 0, 0, 5, 6]]

In [29]:
import numpy as np

In [30]:
season_total = np.add(row_list1, row_list2)
season_total

array([[14,  0,  0, 16, 14,  0, 15,  0, 13,  0, 16, 14, 14,  0],
       [15,  0,  0, 14, 13,  0, 14,  0, 13,  0, 13, 16, 16,  0],
       [14,  0,  0, 16, 16,  0, 14,  0, 14,  0, 14, 16, 16,  0],
       [13,  0, 13, 16, 16, 14, 14,  0, 15,  0, 13, 14, 16,  0],
       [18,  0, 16, 18, 17,  0, 16,  0, 17,  0, 16, 15, 15,  0],
       [16, 17, 16, 18, 19,  0, 16,  0, 16,  0, 18,  0, 16,  0],
       [12, 12,  0, 14, 12,  0, 16,  0, 15,  0, 13,  0, 12,  0],
       [13, 14,  0, 17, 16,  0, 14,  0, 13,  0, 13,  0, 14,  0],
       [14, 17,  0,  0, 14,  0, 14, 14, 15,  0,  0,  0, 16, 16],
       [13, 14,  0,  0, 17,  0, 14,  0, 16, 16,  0,  0, 12, 14]],
      dtype=int64)

In [31]:
season_win = pd.crosstab(ipl['season'], ipl['winner'])
season_win

winner,Chennai Super Kings,Deccan Chargers,Delhi Daredevils,Gujarat Lions,Kings XI Punjab,Kochi Tuskers Kerala,Kolkata Knight Riders,Mumbai Indians,Pune Warriors,Rajasthan Royals,Rising Pune Supergiant,Rising Pune Supergiants,Royal Challengers Bangalore,Sunrisers Hyderabad
season,,,,,,,,,,,,,,
2008,9,2,7,0,10,0,6,7,0,13,0,0,4,0
2009,8,9,10,0,7,0,3,5,0,6,0,0,9,0
2010,9,8,7,0,4,0,7,11,0,6,0,0,8,0
2011,11,6,4,0,7,6,8,10,4,6,0,0,10,0
2012,10,4,11,0,8,0,12,10,4,7,0,0,8,0
2013,12,0,3,0,8,0,6,13,4,11,0,0,9,10
2014,8,0,1,0,11,0,11,7,0,7,0,0,4,4
2015,10,0,5,0,3,0,7,10,0,7,0,0,8,7
2016,0,0,7,9,4,0,8,7,0,0,0,5,9,11
2017,0,0,6,4,7,0,9,12,0,0,10,0,2,8

In [32]:
row_list = []
for index, rows in season_win.iterrows(): 
    my_list = []
    for j in ls:
        my_list.append(rows[j])
    row_list.append(my_list)
row_list

[[7, 0, 0, 9, 7, 0, 10, 0, 6, 0, 13, 2, 4, 0],
 [10, 0, 0, 8, 5, 0, 7, 0, 3, 0, 6, 9, 9, 0],
 [7, 0, 0, 9, 11, 0, 4, 0, 7, 0, 6, 8, 8, 0],
 [4, 0, 4, 11, 10, 6, 7, 0, 8, 0, 6, 6, 10, 0],
 [11, 0, 4, 10, 10, 0, 8, 0, 12, 0, 7, 4, 8, 0],
 [3, 10, 4, 12, 13, 0, 8, 0, 6, 0, 11, 0, 9, 0],
 [1, 4, 0, 8, 7, 0, 11, 0, 11, 0, 7, 0, 4, 0],
 [5, 7, 0, 10, 10, 0, 3, 0, 7, 0, 7, 0, 8, 0],
 [7, 11, 0, 0, 7, 0, 4, 5, 8, 0, 0, 0, 9, 9],
 [6, 8, 0, 0, 12, 0, 7, 0, 9, 10, 0, 0, 2, 4]]

In [33]:
win_p = np.divide(row_list, season_total)
win_p

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.

array([[0.5       ,        nan,        nan, 0.5625    , 0.5       ,
               nan, 0.66666667,        nan, 0.46153846,        nan,
        0.8125    , 0.14285714, 0.28571429,        nan],
       [0.66666667,        nan,        nan, 0.57142857, 0.38461538,
               nan, 0.5       ,        nan, 0.23076923,        nan,
        0.46153846, 0.5625    , 0.5625    ,        nan],
       [0.5       ,        nan,        nan, 0.5625    , 0.6875    ,
               nan, 0.28571429,        nan, 0.5       ,        nan,
        0.42857143, 0.5       , 0.5       ,        nan],
       [0.30769231,        nan, 0.30769231, 0.6875    , 0.625     ,
        0.42857143, 0.5       ,        nan, 0.53333333,        nan,
        0.46153846, 0.42857143, 0.625     ,        nan],
       [0.61111111,        nan, 0.25      , 0.55555556, 0.58823529,
               nan, 0.5       ,        nan, 0.70588235,        nan,
        0.4375    , 0.26666667, 0.53333333,        nan],
       [0.1875    , 0.58823529, 0.25      , 0.66666667, 0.68421053,
               nan, 0.5       ,        nan, 0.375     ,        nan,
        0.61111111,        nan, 0.5625    ,        nan],
       [0.08333333, 0.33333333,        nan, 0.57142857, 0.58333333,
               nan, 0.6875    ,        nan, 0.73333333,        nan,
        0.53846154,        nan, 0.33333333,        nan],
       [0.38461538, 0.5       ,        nan, 0.58823529, 0.625     ,
               nan, 0.21428571,        nan, 0.53846154,        nan,
        0.53846154,        nan, 0.57142857,        nan],
       [0.5       , 0.64705882,        nan,        nan, 0.5       ,
               nan, 0.28571429, 0.35714286, 0.53333333,        nan,
               nan,        nan, 0.5625    , 0.5625    ],
       [0.46153846, 0.57142857,        nan,        nan, 0.70588235,
               nan, 0.5       ,        nan, 0.5625    , 0.625     ,
               nan,        nan, 0.16666667, 0.28571429]])

In [34]:
new_win = []
for row in win_p:
    r = []
    for i in row:
        r.append(round(i* 100, 2))   
    new_win.append(r)
new_win

[[50.0,
  nan,
  nan,
  56.25,
  50.0,
  nan,
  66.67,
  nan,
  46.15,
  nan,
  81.25,
  14.29,
  28.57,
  nan],
 [66.67,
  nan,
  nan,
  57.14,
  38.46,
  nan,
  50.0,
  nan,
  23.08,
  nan,
  46.15,
  56.25,
  56.25,
  nan],
 [50.0,
  nan,
  nan,
  56.25,
  68.75,
  nan,
  28.57,
  nan,
  50.0,
  nan,
  42.86,
  50.0,
  50.0,
  nan],
 [30.77,
  nan,
  30.77,
  68.75,
  62.5,
  42.86,
  50.0,
  nan,
  53.33,
  nan,
  46.15,
  42.86,
  62.5,
  nan],
 [61.11,
  nan,
  25.0,
  55.56,
  58.82,
  nan,
  50.0,
  nan,
  70.59,
  nan,
  43.75,
  26.67,
  53.33,
  nan],
 [18.75,
  58.82,
  25.0,
  66.67,
  68.42,
  nan,
  50.0,
  nan,
  37.5,
  nan,
  61.11,
  nan,
  56.25,
  nan],
 [8.33,
  33.33,
  nan,
  57.14,
  58.33,
  nan,
  68.75,
  nan,
  73.33,
  nan,
  53.85,
  nan,
  33.33,
  nan],
 [38.46,
  50.0,
  nan,
  58.82,
  62.5,
  nan,
  21.43,
  nan,
  53.85,
  nan,
  53.85,
  nan,
  57.14,
  nan],
 [50.0,
  64.71,
  nan,
  nan,
  50.0,
  nan,
  28.57,
  35.71,
  53.33,
  nan,
  nan,
  nan,
  56.25,
  56.25],
 [46.15,
  57.14,
  nan,
  nan,
  70.59,
  nan,
  50.0,
  nan,
  56.25,
  62.5,
  nan,
  nan,
  16.67,
  28.57]]

In [35]:
season1.index

Int64Index([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017], dtype='int64', name='season')

In [36]:
for i in range(len(season1.index)):
    ipl_new[f'Win_Perc{season1.index[i]}'] = new_win[i]
ipl_new

,Team,Total_Wins,Total_Matches,Win_Percentage,Bat_First_Win,Field_First_Win,Favourable_Venue,Win_Perc2008,Win_Perc2009,Win_Perc2010,Win_Perc2011,Win_Perc2012,Win_Perc2013,Win_Perc2014,Win_Perc2015,Win_Perc2016,Win_Perc2017
0,Delhi Daredevils,61,142,42.957746,27,34,Feroz Shah Kotla,50.00,66.67,50.00,30.77,61.11,18.75,8.33,38.46,50.00,46.15
1,Sunrisers Hyderabad,40,114,35.087719,15,25,"Rajiv Gandhi International Stadium, Uppal",NaN,NaN,NaN,NaN,NaN,58.82,33.33,50.00,64.71,57.14
2,Pune Warriors,12,45,26.666667,9,3,Subrata Roy Sahara Stadium,NaN,NaN,NaN,30.77,25.00,25.00,NaN,NaN,NaN,NaN
3,Chennai Super Kings,77,129,59.689922,49,28,"MA Chidambaram Stadium, Chepauk",56.25,57.14,56.25,68.75,55.56,66.67,57.14,58.82,NaN,NaN
4,Mumbai Indians,92,154,59.740260,41,51,Wankhede Stadium,50.00,38.46,68.75,62.50,58.82,68.42,58.33,62.50,50.00,70.59
5,Kochi Tuskers Kerala,6,37,16.216216,0,6,Nehru Stadium,NaN,NaN,NaN,42.86,NaN,NaN,NaN,NaN,NaN,NaN
6,Kings XI Punjab,69,84,82.142857,20,49,"Punjab Cricket Association Stadium, Mohali",66.67,50.00,28.57,50.00,50.00,50.00,68.75,21.43,28.57,50.00
7,Rising Pune Supergiants,5,14,35.714286,2,3,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.71,NaN
8,Kolkata Knight Riders,77,147,52.380952,34,43,Eden Gardens,46.15,23.08,50.00,53.33,70.59,37.50,73.33,53.85,53.33,56.25
9,Rising Pune Supergiant,10,16,62.500000,0,10,Maharashtra Cricket Association Stadium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.50
10,Rajasthan Royals,63,116,54.310345,30,33,Sawai Mansingh Stadium,81.25,46.15,42.86,46.15,43.75,61.11,53.85,53.85,NaN,NaN
11,Deccan Chargers,29,75,38.666667,14,15,Barabati Stadium,14.29,56.25,50.00,42.86,26.67,NaN,NaN,NaN,NaN,NaN
12,Royal Challengers Bangalore,71,147,48.299320,25,46,M Chinnaswamy Stadium,28.57,56.25,50.00,62.50,53.33,56.25,33.33,57.14,56.25,16.67
13,Gujarat Lions,13,30,43.333333,2,11,Saurashtra Cricket Association Stadium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.25,28.57

In [37]:
ipl_new.fillna(0, inplace=True)
ipl_new

,Team,Total_Wins,Total_Matches,Win_Percentage,Bat_First_Win,Field_First_Win,Favourable_Venue,Win_Perc2008,Win_Perc2009,Win_Perc2010,Win_Perc2011,Win_Perc2012,Win_Perc2013,Win_Perc2014,Win_Perc2015,Win_Perc2016,Win_Perc2017
0,Delhi Daredevils,61,142,42.957746,27,34,Feroz Shah Kotla,50.00,66.67,50.00,30.77,61.11,18.75,8.33,38.46,50.00,46.15
1,Sunrisers Hyderabad,40,114,35.087719,15,25,"Rajiv Gandhi International Stadium, Uppal",0.00,0.00,0.00,0.00,0.00,58.82,33.33,50.00,64.71,57.14
2,Pune Warriors,12,45,26.666667,9,3,Subrata Roy Sahara Stadium,0.00,0.00,0.00,30.77,25.00,25.00,0.00,0.00,0.00,0.00
3,Chennai Super Kings,77,129,59.689922,49,28,"MA Chidambaram Stadium, Chepauk",56.25,57.14,56.25,68.75,55.56,66.67,57.14,58.82,0.00,0.00
4,Mumbai Indians,92,154,59.740260,41,51,Wankhede Stadium,50.00,38.46,68.75,62.50,58.82,68.42,58.33,62.50,50.00,70.59
5,Kochi Tuskers Kerala,6,37,16.216216,0,6,Nehru Stadium,0.00,0.00,0.00,42.86,0.00,0.00,0.00,0.00,0.00,0.00
6,Kings XI Punjab,69,84,82.142857,20,49,"Punjab Cricket Association Stadium, Mohali",66.67,50.00,28.57,50.00,50.00,50.00,68.75,21.43,28.57,50.00
7,Rising Pune Supergiants,5,14,35.714286,2,3,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,35.71,0.00
8,Kolkata Knight Riders,77,147,52.380952,34,43,Eden Gardens,46.15,23.08,50.00,53.33,70.59,37.50,73.33,53.85,53.33,56.25
9,Rising Pune Supergiant,10,16,62.500000,0,10,Maharashtra Cricket Association Stadium,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,62.50
10,Rajasthan Royals,63,116,54.310345,30,33,Sawai Mansingh Stadium,81.25,46.15,42.86,46.15,43.75,61.11,53.85,53.85,0.00,0.00
11,Deccan Chargers,29,75,38.666667,14,15,Barabati Stadium,14.29,56.25,50.00,42.86,26.67,0.00,0.00,0.00,0.00,0.00
12,Royal Challengers Bangalore,71,147,48.299320,25,46,M Chinnaswamy Stadium,28.57,56.25,50.00,62.50,53.33,56.25,33.33,57.14,56.25,16.67
13,Gujarat Lions,13,30,43.333333,2,11,Saurashtra Cricket Association Stadium,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,56.25,28.57

In [38]:
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,Hyderabad,05-04-17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,Pune,06-04-17,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi
2,3,2017,Rajkot,07-04-17,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan
3,4,2017,Indore,08-04-17,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin
5,6,2017,Hyderabad,09-04-17,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong

### Toss Winning Percentage

In [39]:
win_toss = []
tw = ipl['toss_winner'].value_counts().index.tolist()
tw_val = ipl['toss_winner'].value_counts().tolist()
for i in range(len(tw)):
    win_toss.append((tw[i], tw_val[i]))
win_toss

[('Mumbai Indians', 83),
 ('Kolkata Knight Riders', 77),
 ('Delhi Daredevils', 71),
 ('Royal Challengers Bangalore', 67),
 ('Kings XI Punjab', 67),
 ('Chennai Super Kings', 66),
 ('Rajasthan Royals', 61),
 ('Deccan Chargers', 43),
 ('Sunrisers Hyderabad', 34),
 ('Pune Warriors', 20),
 ('Gujarat Lions', 15),
 ('Kochi Tuskers Kerala', 8),
 ('Rising Pune Supergiants', 7),
 ('Rising Pune Supergiant', 6)]

In [40]:
toss_win = []
for i in ls:
    for j in win_toss:
        if i == j[0]:
            toss_win.append(j[1])
toss_win

[71, 34, 20, 66, 83, 8, 67, 7, 77, 6, 61, 43, 67, 15]

In [41]:
tm = ipl_new['Total_Matches'].tolist()
tm

[142, 114, 45, 129, 154, 37, 84, 14, 147, 16, 116, 75, 147, 30]

In [42]:
twp_new = []
twp = np.multiply(np.divide(toss_win, tm), 100)
for i in twp:
    twp_new.append(round(i, 2))
twp_new

[50.0,
 29.82,
 44.44,
 51.16,
 53.9,
 21.62,
 79.76,
 50.0,
 52.38,
 37.5,
 52.59,
 57.33,
 45.58,
 50.0]

In [43]:
ipl_new['Toss_Win'] = twp_new
ipl_new

,Team,Total_Wins,Total_Matches,Win_Percentage,Bat_First_Win,Field_First_Win,Favourable_Venue,Win_Perc2008,Win_Perc2009,Win_Perc2010,Win_Perc2011,Win_Perc2012,Win_Perc2013,Win_Perc2014,Win_Perc2015,Win_Perc2016,Win_Perc2017,Toss_Win
0,Delhi Daredevils,61,142,42.957746,27,34,Feroz Shah Kotla,50.00,66.67,50.00,30.77,61.11,18.75,8.33,38.46,50.00,46.15,50.00
1,Sunrisers Hyderabad,40,114,35.087719,15,25,"Rajiv Gandhi International Stadium, Uppal",0.00,0.00,0.00,0.00,0.00,58.82,33.33,50.00,64.71,57.14,29.82
2,Pune Warriors,12,45,26.666667,9,3,Subrata Roy Sahara Stadium,0.00,0.00,0.00,30.77,25.00,25.00,0.00,0.00,0.00,0.00,44.44
3,Chennai Super Kings,77,129,59.689922,49,28,"MA Chidambaram Stadium, Chepauk",56.25,57.14,56.25,68.75,55.56,66.67,57.14,58.82,0.00,0.00,51.16
4,Mumbai Indians,92,154,59.740260,41,51,Wankhede Stadium,50.00,38.46,68.75,62.50,58.82,68.42,58.33,62.50,50.00,70.59,53.90
5,Kochi Tuskers Kerala,6,37,16.216216,0,6,Nehru Stadium,0.00,0.00,0.00,42.86,0.00,0.00,0.00,0.00,0.00,0.00,21.62
6,Kings XI Punjab,69,84,82.142857,20,49,"Punjab Cricket Association Stadium, Mohali",66.67,50.00,28.57,50.00,50.00,50.00,68.75,21.43,28.57,50.00,79.76
7,Rising Pune Supergiants,5,14,35.714286,2,3,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,35.71,0.00,50.00
8,Kolkata Knight Riders,77,147,52.380952,34,43,Eden Gardens,46.15,23.08,50.00,53.33,70.59,37.50,73.33,53.85,53.33,56.25,52.38
9,Rising Pune Supergiant,10,16,62.500000,0,10,Maharashtra Cricket Association Stadium,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,62.50,37.50
10,Rajasthan Royals,63,116,54.310345,30,33,Sawai Mansingh Stadium,81.25,46.15,42.86,46.15,43.75,61.11,53.85,53.85,0.00,0.00,52.59
11,Deccan Chargers,29,75,38.666667,14,15,Barabati Stadium,14.29,56.25,50.00,42.86,26.67,0.00,0.00,0.00,0.00,0.00,57.33
12,Royal Challengers Bangalore,71,147,48.299320,25,46,M Chinnaswamy Stadium,28.57,56.25,50.00,62.50,53.33,56.25,33.33,57.14,56.25,16.67,45.58
13,Gujarat Lions,13,30,43.333333,2,11,Saurashtra Cricket Association Stadium,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,56.25,28.57,50.00

In [44]:
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,Hyderabad,05-04-17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,Pune,06-04-17,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi
2,3,2017,Rajkot,07-04-17,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan
3,4,2017,Indore,08-04-17,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin
5,6,2017,Hyderabad,09-04-17,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong

### Season Active

In [73]:
s_active = ['2008 - 2015',
 '2017',
 '2008 - 2017',
 '2016 - 2017',
 '2008 - 2017',
 '2008 - 2012',
 '2008 - 2017',
 '2008 - 2015',
 '2008 - 2017',
 '2011 - 2013',
 '2017',
 '2013 - 2017',
 '2011',
 '2008 - 2017']
t = [
    "Chennai Super Kings",
    "Rising Pune Supergiants",
    "Royal Challengers Bangalore",
    "Gujarat Lions",
    "Mumbai Indians",
    "Deccan Chargers",
    "Kings XI Punjab",
    "Rajasthan Royals",
    "Delhi Daredevils",
    "Pune Warriors",
    "Rising Pune Supergiant",
    "Sunrisers Hyderabad",
    "Kochi Tuskers Kerala",
    "Kolkata Knight Riders"
]

s_new = []
for i in ls:
    x = t.index(i)
    s_new.append(s_active[x])
s_new
ipl_new['Seaon_Active'] = s_new

In [74]:
ipl_new

,Team,Total_Wins,Total_Matches,Win_Percentage,Bat_First_Win,Field_First_Win,Favourable_Venue,Win_Perc2008,Win_Perc2009,Win_Perc2010,...,Win_Perc2014,Win_Perc2015,Win_Perc2016,Win_Perc2017,Toss_Win,Seaon_Active,MVP,Max_Umpire1,Max_Umpire2,Most_Played
0,Delhi Daredevils,61,142,42.957746,27,34,Feroz Shah Kotla,50.00,66.67,50.00,...,8.33,38.46,50.00,46.15,50.00,2008 - 2017,V Sehwag,BF Bowden,S Ravi,Mumbai Indians
1,Sunrisers Hyderabad,40,114,35.087719,15,25,"Rajiv Gandhi International Stadium, Uppal",0.00,0.00,0.00,...,33.33,50.00,64.71,57.14,29.82,2013 - 2017,DA Warner,AK Chaudhary,NJ Llong,Gujarat Lions
2,Pune Warriors,12,45,26.666667,9,3,Subrata Roy Sahara Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,44.44,2011 - 2013,SPD Smith,Asad Rauf,SJA Taufel,Chennai Super Kings
3,Chennai Super Kings,77,129,59.689922,49,28,"MA Chidambaram Stadium, Chepauk",56.25,57.14,56.25,...,57.14,58.82,0.00,0.00,51.16,2008 - 2015,SK Raina,Asad Rauf,SJA Taufel,Mumbai Indians
4,Mumbai Indians,92,154,59.740260,41,51,Wankhede Stadium,50.00,38.46,68.75,...,58.33,62.50,50.00,70.59,53.90,2008 - 2017,RG Sharma,HDPK Dharmasena,SJA Taufel,Kings XI Punjab
5,Kochi Tuskers Kerala,6,37,16.216216,0,6,Nehru Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,21.62,2011,BB McCullum,Aleem Dar,RJ Tucker,Chennai Super Kings
6,Kings XI Punjab,69,84,82.142857,20,49,"Punjab Cricket Association Stadium, Mohali",66.67,50.00,28.57,...,68.75,21.43,28.57,50.00,79.76,2008 - 2017,SE Marsh,HDPK Dharmasena,C Shamshuddin,Royal Challengers Bangalore
7,Rising Pune Supergiants,5,14,35.714286,2,3,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,0.00,0.00,0.00,...,0.00,0.00,35.71,0.00,50.00,2017,AB Dinda,HDPK Dharmasena,CK Nandan,Delhi Daredevils
8,Kolkata Knight Riders,77,147,52.380952,34,43,Eden Gardens,46.15,23.08,50.00,...,73.33,53.85,53.33,56.25,52.38,2008 - 2017,G Gambhir,AK Chaudhary,CK Nandan,Kings XI Punjab
9,Rising Pune Supergiant,10,16,62.500000,0,10,Maharashtra Cricket Association Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,62.50,37.50,2017,BA Stokes,KN Ananthapadmanabhan,C Shamshuddin,Delhi Daredevils
10,Rajasthan Royals,63,116,54.310345,30,33,Sawai Mansingh Stadium,81.25,46.15,42.86,...,53.85,53.85,0.00,0.00,52.59,2008 - 2015,AM Rahane,Aleem Dar,SK Tarapore,Mumbai Indians
11,Deccan Chargers,29,75,38.666667,14,15,Barabati Stadium,14.29,56.25,50.00,...,0.00,0.00,0.00,0.00,57.33,2008 - 2012,AC Gilchrist,S Ravi,SJA Taufel,Chennai Super Kings
12,Royal Challengers Bangalore,71,147,48.299320,25,46,M Chinnaswamy Stadium,28.57,56.25,50.00,...,33.33,57.14,56.25,16.67,45.58,2008 - 2017,CH Gayle,HDPK Dharmasena,C Shamshuddin,Kolkata Knight Riders
13,Gujarat Lions,13,30,43.333333,2,11,Saurashtra Cricket Association Stadium,0.00,0.00,0.00,...,0.00,0.00,56.25,28.57,50.00,2016 - 2017,AJ Finch,AK Chaudhary,CK Nandan,Kings XI Punjab

In [75]:
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,Hyderabad,05-04-17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,Pune,06-04-17,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi
2,3,2017,Rajkot,07-04-17,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan
3,4,2017,Indore,08-04-17,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin
5,6,2017,Hyderabad,09-04-17,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong

### Maximum Player of the match for each team

In [76]:
# max time player of match
df = pd.crosstab(ipl['winner'], ipl['player_of_match'])
tp = df.idxmax(axis=1).index.tolist()
pp = df.idxmax(axis=1).tolist()

In [77]:
tpp = []
for i in range(len(tp)):
    tpp.append((tp[i], pp[i]))
tpp

[('Chennai Super Kings', 'SK Raina'),
 ('Deccan Chargers', 'AC Gilchrist'),
 ('Delhi Daredevils', 'V Sehwag'),
 ('Gujarat Lions', 'AJ Finch'),
 ('Kings XI Punjab', 'SE Marsh'),
 ('Kochi Tuskers Kerala', 'BB McCullum'),
 ('Kolkata Knight Riders', 'G Gambhir'),
 ('Mumbai Indians', 'RG Sharma'),
 ('Pune Warriors', 'SPD Smith'),
 ('Rajasthan Royals', 'AM Rahane'),
 ('Rising Pune Supergiant', 'BA Stokes'),
 ('Rising Pune Supergiants', 'AB Dinda'),
 ('Royal Challengers Bangalore', 'CH Gayle'),
 ('Sunrisers Hyderabad', 'DA Warner')]

In [78]:
mvp = []
for i in ls:
    for j in tpp:
        if i == j[0]:
            mvp.append(j[1])
mvp

['V Sehwag',
 'DA Warner',
 'SPD Smith',
 'SK Raina',
 'RG Sharma',
 'BB McCullum',
 'SE Marsh',
 'AB Dinda',
 'G Gambhir',
 'BA Stokes',
 'AM Rahane',
 'AC Gilchrist',
 'CH Gayle',
 'AJ Finch']

In [79]:
ipl_new['MVP'] = mvp
ipl_new

,Team,Total_Wins,Total_Matches,Win_Percentage,Bat_First_Win,Field_First_Win,Favourable_Venue,Win_Perc2008,Win_Perc2009,Win_Perc2010,...,Win_Perc2014,Win_Perc2015,Win_Perc2016,Win_Perc2017,Toss_Win,Seaon_Active,MVP,Max_Umpire1,Max_Umpire2,Most_Played
0,Delhi Daredevils,61,142,42.957746,27,34,Feroz Shah Kotla,50.00,66.67,50.00,...,8.33,38.46,50.00,46.15,50.00,2008 - 2017,V Sehwag,BF Bowden,S Ravi,Mumbai Indians
1,Sunrisers Hyderabad,40,114,35.087719,15,25,"Rajiv Gandhi International Stadium, Uppal",0.00,0.00,0.00,...,33.33,50.00,64.71,57.14,29.82,2013 - 2017,DA Warner,AK Chaudhary,NJ Llong,Gujarat Lions
2,Pune Warriors,12,45,26.666667,9,3,Subrata Roy Sahara Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,44.44,2011 - 2013,SPD Smith,Asad Rauf,SJA Taufel,Chennai Super Kings
3,Chennai Super Kings,77,129,59.689922,49,28,"MA Chidambaram Stadium, Chepauk",56.25,57.14,56.25,...,57.14,58.82,0.00,0.00,51.16,2008 - 2015,SK Raina,Asad Rauf,SJA Taufel,Mumbai Indians
4,Mumbai Indians,92,154,59.740260,41,51,Wankhede Stadium,50.00,38.46,68.75,...,58.33,62.50,50.00,70.59,53.90,2008 - 2017,RG Sharma,HDPK Dharmasena,SJA Taufel,Kings XI Punjab
5,Kochi Tuskers Kerala,6,37,16.216216,0,6,Nehru Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,21.62,2011,BB McCullum,Aleem Dar,RJ Tucker,Chennai Super Kings
6,Kings XI Punjab,69,84,82.142857,20,49,"Punjab Cricket Association Stadium, Mohali",66.67,50.00,28.57,...,68.75,21.43,28.57,50.00,79.76,2008 - 2017,SE Marsh,HDPK Dharmasena,C Shamshuddin,Royal Challengers Bangalore
7,Rising Pune Supergiants,5,14,35.714286,2,3,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,0.00,0.00,0.00,...,0.00,0.00,35.71,0.00,50.00,2017,AB Dinda,HDPK Dharmasena,CK Nandan,Delhi Daredevils
8,Kolkata Knight Riders,77,147,52.380952,34,43,Eden Gardens,46.15,23.08,50.00,...,73.33,53.85,53.33,56.25,52.38,2008 - 2017,G Gambhir,AK Chaudhary,CK Nandan,Kings XI Punjab
9,Rising Pune Supergiant,10,16,62.500000,0,10,Maharashtra Cricket Association Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,62.50,37.50,2017,BA Stokes,KN Ananthapadmanabhan,C Shamshuddin,Delhi Daredevils
10,Rajasthan Royals,63,116,54.310345,30,33,Sawai Mansingh Stadium,81.25,46.15,42.86,...,53.85,53.85,0.00,0.00,52.59,2008 - 2015,AM Rahane,Aleem Dar,SK Tarapore,Mumbai Indians
11,Deccan Chargers,29,75,38.666667,14,15,Barabati Stadium,14.29,56.25,50.00,...,0.00,0.00,0.00,0.00,57.33,2008 - 2012,AC Gilchrist,S Ravi,SJA Taufel,Chennai Super Kings
12,Royal Challengers Bangalore,71,147,48.299320,25,46,M Chinnaswamy Stadium,28.57,56.25,50.00,...,33.33,57.14,56.25,16.67,45.58,2008 - 2017,CH Gayle,HDPK Dharmasena,C Shamshuddin,Kolkata Knight Riders
13,Gujarat Lions,13,30,43.333333,2,11,Saurashtra Cricket Association Stadium,0.00,0.00,0.00,...,0.00,0.00,56.25,28.57,50.00,2016 - 2017,AJ Finch,AK Chaudhary,CK Nandan,Kings XI Punjab

In [80]:
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,Hyderabad,05-04-17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,Pune,06-04-17,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi
2,3,2017,Rajkot,07-04-17,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan
3,4,2017,Indore,08-04-17,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin
5,6,2017,Hyderabad,09-04-17,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong

### Most Times umpire 1 and umpire 2 for each team

In [81]:
# max umpire 1
df = pd.crosstab(ipl['winner'], ipl['umpire1'])
up = df.idxmax(axis=1).index.tolist()
pp = df.idxmax(axis=1).tolist()

In [82]:
upp = []
for i in range(len(up)):
    upp.append((up[i], pp[i]))
upp

[('Chennai Super Kings', 'Asad Rauf'),
 ('Deccan Chargers', 'S Ravi'),
 ('Delhi Daredevils', 'BF Bowden'),
 ('Gujarat Lions', 'AK Chaudhary'),
 ('Kings XI Punjab', 'HDPK Dharmasena'),
 ('Kochi Tuskers Kerala', 'Aleem Dar'),
 ('Kolkata Knight Riders', 'AK Chaudhary'),
 ('Mumbai Indians', 'HDPK Dharmasena'),
 ('Pune Warriors', 'Asad Rauf'),
 ('Rajasthan Royals', 'Aleem Dar'),
 ('Rising Pune Supergiant', 'KN Ananthapadmanabhan'),
 ('Rising Pune Supergiants', 'HDPK Dharmasena'),
 ('Royal Challengers Bangalore', 'HDPK Dharmasena'),
 ('Sunrisers Hyderabad', 'AK Chaudhary')]

In [83]:
# max umpire 2
df = pd.crosstab(ipl['winner'], ipl['umpire2'])
up1 = df.idxmax(axis=1).index.tolist()
pp1 = df.idxmax(axis=1).tolist()

In [84]:
upp1 = []
for i in range(len(up1)):
    upp1.append((up1[i], pp1[i]))
upp1

[('Chennai Super Kings', 'SJA Taufel'),
 ('Deccan Chargers', 'SJA Taufel'),
 ('Delhi Daredevils', 'S Ravi'),
 ('Gujarat Lions', 'CK Nandan'),
 ('Kings XI Punjab', 'C Shamshuddin'),
 ('Kochi Tuskers Kerala', 'RJ Tucker'),
 ('Kolkata Knight Riders', 'CK Nandan'),
 ('Mumbai Indians', 'SJA Taufel'),
 ('Pune Warriors', 'SJA Taufel'),
 ('Rajasthan Royals', 'SK Tarapore'),
 ('Rising Pune Supergiant', 'C Shamshuddin'),
 ('Rising Pune Supergiants', 'CK Nandan'),
 ('Royal Challengers Bangalore', 'C Shamshuddin'),
 ('Sunrisers Hyderabad', 'NJ Llong')]

In [85]:
ump1 = []
for i in ls:
    for j in upp:
        if i == j[0]:
            ump1.append(j[1])
ump1

['BF Bowden',
 'AK Chaudhary',
 'Asad Rauf',
 'Asad Rauf',
 'HDPK Dharmasena',
 'Aleem Dar',
 'HDPK Dharmasena',
 'HDPK Dharmasena',
 'AK Chaudhary',
 'KN Ananthapadmanabhan',
 'Aleem Dar',
 'S Ravi',
 'HDPK Dharmasena',
 'AK Chaudhary']

In [86]:
ump2 = []
for i in ls:
    for j in upp1:
        if i == j[0]:
            ump2.append(j[1])
ump2

['S Ravi',
 'NJ Llong',
 'SJA Taufel',
 'SJA Taufel',
 'SJA Taufel',
 'RJ Tucker',
 'C Shamshuddin',
 'CK Nandan',
 'CK Nandan',
 'C Shamshuddin',
 'SK Tarapore',
 'SJA Taufel',
 'C Shamshuddin',
 'CK Nandan']

In [87]:
ipl_new['Max_Umpire1'] = ump1
ipl_new['Max_Umpire2'] = ump2
ipl_new

,Team,Total_Wins,Total_Matches,Win_Percentage,Bat_First_Win,Field_First_Win,Favourable_Venue,Win_Perc2008,Win_Perc2009,Win_Perc2010,...,Win_Perc2014,Win_Perc2015,Win_Perc2016,Win_Perc2017,Toss_Win,Seaon_Active,MVP,Max_Umpire1,Max_Umpire2,Most_Played
0,Delhi Daredevils,61,142,42.957746,27,34,Feroz Shah Kotla,50.00,66.67,50.00,...,8.33,38.46,50.00,46.15,50.00,2008 - 2017,V Sehwag,BF Bowden,S Ravi,Mumbai Indians
1,Sunrisers Hyderabad,40,114,35.087719,15,25,"Rajiv Gandhi International Stadium, Uppal",0.00,0.00,0.00,...,33.33,50.00,64.71,57.14,29.82,2013 - 2017,DA Warner,AK Chaudhary,NJ Llong,Gujarat Lions
2,Pune Warriors,12,45,26.666667,9,3,Subrata Roy Sahara Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,44.44,2011 - 2013,SPD Smith,Asad Rauf,SJA Taufel,Chennai Super Kings
3,Chennai Super Kings,77,129,59.689922,49,28,"MA Chidambaram Stadium, Chepauk",56.25,57.14,56.25,...,57.14,58.82,0.00,0.00,51.16,2008 - 2015,SK Raina,Asad Rauf,SJA Taufel,Mumbai Indians
4,Mumbai Indians,92,154,59.740260,41,51,Wankhede Stadium,50.00,38.46,68.75,...,58.33,62.50,50.00,70.59,53.90,2008 - 2017,RG Sharma,HDPK Dharmasena,SJA Taufel,Kings XI Punjab
5,Kochi Tuskers Kerala,6,37,16.216216,0,6,Nehru Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,21.62,2011,BB McCullum,Aleem Dar,RJ Tucker,Chennai Super Kings
6,Kings XI Punjab,69,84,82.142857,20,49,"Punjab Cricket Association Stadium, Mohali",66.67,50.00,28.57,...,68.75,21.43,28.57,50.00,79.76,2008 - 2017,SE Marsh,HDPK Dharmasena,C Shamshuddin,Royal Challengers Bangalore
7,Rising Pune Supergiants,5,14,35.714286,2,3,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,0.00,0.00,0.00,...,0.00,0.00,35.71,0.00,50.00,2017,AB Dinda,HDPK Dharmasena,CK Nandan,Delhi Daredevils
8,Kolkata Knight Riders,77,147,52.380952,34,43,Eden Gardens,46.15,23.08,50.00,...,73.33,53.85,53.33,56.25,52.38,2008 - 2017,G Gambhir,AK Chaudhary,CK Nandan,Kings XI Punjab
9,Rising Pune Supergiant,10,16,62.500000,0,10,Maharashtra Cricket Association Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,62.50,37.50,2017,BA Stokes,KN Ananthapadmanabhan,C Shamshuddin,Delhi Daredevils
10,Rajasthan Royals,63,116,54.310345,30,33,Sawai Mansingh Stadium,81.25,46.15,42.86,...,53.85,53.85,0.00,0.00,52.59,2008 - 2015,AM Rahane,Aleem Dar,SK Tarapore,Mumbai Indians
11,Deccan Chargers,29,75,38.666667,14,15,Barabati Stadium,14.29,56.25,50.00,...,0.00,0.00,0.00,0.00,57.33,2008 - 2012,AC Gilchrist,S Ravi,SJA Taufel,Chennai Super Kings
12,Royal Challengers Bangalore,71,147,48.299320,25,46,M Chinnaswamy Stadium,28.57,56.25,50.00,...,33.33,57.14,56.25,16.67,45.58,2008 - 2017,CH Gayle,HDPK Dharmasena,C Shamshuddin,Kolkata Knight Riders
13,Gujarat Lions,13,30,43.333333,2,11,Saurashtra Cricket Association Stadium,0.00,0.00,0.00,...,0.00,0.00,56.25,28.57,50.00,2016 - 2017,AJ Finch,AK Chaudhary,CK Nandan,Kings XI Punjab

In [88]:
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,Hyderabad,05-04-17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,Pune,06-04-17,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi
2,3,2017,Rajkot,07-04-17,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan
3,4,2017,Indore,08-04-17,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin
5,6,2017,Hyderabad,09-04-17,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong

In [89]:
ipl_new.head()

,Team,Total_Wins,Total_Matches,Win_Percentage,Bat_First_Win,Field_First_Win,Favourable_Venue,Win_Perc2008,Win_Perc2009,Win_Perc2010,...,Win_Perc2014,Win_Perc2015,Win_Perc2016,Win_Perc2017,Toss_Win,Seaon_Active,MVP,Max_Umpire1,Max_Umpire2,Most_Played
0,Delhi Daredevils,61,142,42.957746,27,34,Feroz Shah Kotla,50.00,66.67,50.00,...,8.33,38.46,50.00,46.15,50.00,2008 - 2017,V Sehwag,BF Bowden,S Ravi,Mumbai Indians
1,Sunrisers Hyderabad,40,114,35.087719,15,25,"Rajiv Gandhi International Stadium, Uppal",0.00,0.00,0.00,...,33.33,50.00,64.71,57.14,29.82,2013 - 2017,DA Warner,AK Chaudhary,NJ Llong,Gujarat Lions
2,Pune Warriors,12,45,26.666667,9,3,Subrata Roy Sahara Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,44.44,2011 - 2013,SPD Smith,Asad Rauf,SJA Taufel,Chennai Super Kings
3,Chennai Super Kings,77,129,59.689922,49,28,"MA Chidambaram Stadium, Chepauk",56.25,57.14,56.25,...,57.14,58.82,0.00,0.00,51.16,2008 - 2015,SK Raina,Asad Rauf,SJA Taufel,Mumbai Indians
4,Mumbai Indians,92,154,59.740260,41,51,Wankhede Stadium,50.00,38.46,68.75,...,58.33,62.50,50.00,70.59,53.90,2008 - 2017,RG Sharma,HDPK Dharmasena,SJA Taufel,Kings XI Punjab

### Most Played Against

In [90]:
defi = pd.crosstab(ipl['team1'], ipl['team2'])
defi

team2,Chennai Super Kings,Deccan Chargers,Delhi Daredevils,Gujarat Lions,Kings XI Punjab,Kochi Tuskers Kerala,Kolkata Knight Riders,Mumbai Indians,Pune Warriors,Rajasthan Royals,Rising Pune Supergiant,Rising Pune Supergiants,Royal Challengers Bangalore,Sunrisers Hyderabad
team1,,,,,,,,,,,,,,
Chennai Super Kings,0,8,11,0,9,2,11,10,4,8,0,0,10,3
Deccan Chargers,2,0,8,0,7,1,2,5,3,7,0,0,8,0
Delhi Daredevils,5,3,0,0,10,2,9,5,1,9,2,2,9,4
Gujarat Lions,0,0,4,0,0,0,1,2,0,0,1,0,1,5
Kings XI Punjab,8,3,10,4,0,0,16,13,2,8,1,1,7,4
Kochi Tuskers Kerala,0,0,0,0,1,0,2,0,1,1,0,0,2,0
Kolkata Knight Riders,5,7,9,3,5,0,0,12,3,1,1,0,16,5
Mumbai Indians,11,5,15,2,7,1,9,0,3,10,2,1,10,4
Pune Warriors,2,1,4,0,4,0,2,3,0,3,0,0,1,0
Rajasthan Royals,8,2,7,0,7,1,14,6,2,0,0,0,7,0
Rising Pune Supergiant,0,0,0,1,1,0,1,2,0,0,0,0,2,1
Rising Pune Supergiants,0,0,0,2,1,0,2,1,0,0,0,0,1,0
Royal Challengers Bangalore,9,3,8,4,12,0,4,10,4,8,0,1,0,4
Sunrisers Hyderabad,3,0,5,0,6,0,7,5,2,7,1,2,6,0

In [91]:
defi_id = defi.idxmax(axis=0).index.tolist()
defi_val = defi.idxmax(axis=0).tolist()
defi_val

['Mumbai Indians',
 'Chennai Super Kings',
 'Mumbai Indians',
 'Kings XI Punjab',
 'Royal Challengers Bangalore',
 'Chennai Super Kings',
 'Kings XI Punjab',
 'Kings XI Punjab',
 'Chennai Super Kings',
 'Mumbai Indians',
 'Delhi Daredevils',
 'Delhi Daredevils',
 'Kolkata Knight Riders',
 'Gujarat Lions']

In [92]:
res = []
for i in ls:
    idx = defi_id.index(i)
    res.append(defi_val[idx])
res

['Mumbai Indians',
 'Gujarat Lions',
 'Chennai Super Kings',
 'Mumbai Indians',
 'Kings XI Punjab',
 'Chennai Super Kings',
 'Royal Challengers Bangalore',
 'Delhi Daredevils',
 'Kings XI Punjab',
 'Delhi Daredevils',
 'Mumbai Indians',
 'Chennai Super Kings',
 'Kolkata Knight Riders',
 'Kings XI Punjab']

In [93]:
ipl_new['Most_Played'] = res
ipl_new

,Team,Total_Wins,Total_Matches,Win_Percentage,Bat_First_Win,Field_First_Win,Favourable_Venue,Win_Perc2008,Win_Perc2009,Win_Perc2010,...,Win_Perc2014,Win_Perc2015,Win_Perc2016,Win_Perc2017,Toss_Win,Seaon_Active,MVP,Max_Umpire1,Max_Umpire2,Most_Played
0,Delhi Daredevils,61,142,42.957746,27,34,Feroz Shah Kotla,50.00,66.67,50.00,...,8.33,38.46,50.00,46.15,50.00,2008 - 2017,V Sehwag,BF Bowden,S Ravi,Mumbai Indians
1,Sunrisers Hyderabad,40,114,35.087719,15,25,"Rajiv Gandhi International Stadium, Uppal",0.00,0.00,0.00,...,33.33,50.00,64.71,57.14,29.82,2013 - 2017,DA Warner,AK Chaudhary,NJ Llong,Gujarat Lions
2,Pune Warriors,12,45,26.666667,9,3,Subrata Roy Sahara Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,44.44,2011 - 2013,SPD Smith,Asad Rauf,SJA Taufel,Chennai Super Kings
3,Chennai Super Kings,77,129,59.689922,49,28,"MA Chidambaram Stadium, Chepauk",56.25,57.14,56.25,...,57.14,58.82,0.00,0.00,51.16,2008 - 2015,SK Raina,Asad Rauf,SJA Taufel,Mumbai Indians
4,Mumbai Indians,92,154,59.740260,41,51,Wankhede Stadium,50.00,38.46,68.75,...,58.33,62.50,50.00,70.59,53.90,2008 - 2017,RG Sharma,HDPK Dharmasena,SJA Taufel,Kings XI Punjab
5,Kochi Tuskers Kerala,6,37,16.216216,0,6,Nehru Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,21.62,2011,BB McCullum,Aleem Dar,RJ Tucker,Chennai Super Kings
6,Kings XI Punjab,69,84,82.142857,20,49,"Punjab Cricket Association Stadium, Mohali",66.67,50.00,28.57,...,68.75,21.43,28.57,50.00,79.76,2008 - 2017,SE Marsh,HDPK Dharmasena,C Shamshuddin,Royal Challengers Bangalore
7,Rising Pune Supergiants,5,14,35.714286,2,3,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,0.00,0.00,0.00,...,0.00,0.00,35.71,0.00,50.00,2017,AB Dinda,HDPK Dharmasena,CK Nandan,Delhi Daredevils
8,Kolkata Knight Riders,77,147,52.380952,34,43,Eden Gardens,46.15,23.08,50.00,...,73.33,53.85,53.33,56.25,52.38,2008 - 2017,G Gambhir,AK Chaudhary,CK Nandan,Kings XI Punjab
9,Rising Pune Supergiant,10,16,62.500000,0,10,Maharashtra Cricket Association Stadium,0.00,0.00,0.00,...,0.00,0.00,0.00,62.50,37.50,2017,BA Stokes,KN Ananthapadmanabhan,C Shamshuddin,Delhi Daredevils
10,Rajasthan Royals,63,116,54.310345,30,33,Sawai Mansingh Stadium,81.25,46.15,42.86,...,53.85,53.85,0.00,0.00,52.59,2008 - 2015,AM Rahane,Aleem Dar,SK Tarapore,Mumbai Indians
11,Deccan Chargers,29,75,38.666667,14,15,Barabati Stadium,14.29,56.25,50.00,...,0.00,0.00,0.00,0.00,57.33,2008 - 2012,AC Gilchrist,S Ravi,SJA Taufel,Chennai Super Kings
12,Royal Challengers Bangalore,71,147,48.299320,25,46,M Chinnaswamy Stadium,28.57,56.25,50.00,...,33.33,57.14,56.25,16.67,45.58,2008 - 2017,CH Gayle,HDPK Dharmasena,C Shamshuddin,Kolkata Knight Riders
13,Gujarat Lions,13,30,43.333333,2,11,Saurashtra Cricket Association Stadium,0.00,0.00,0.00,...,0.00,0.00,56.25,28.57,50.00,2016 - 2017,AJ Finch,AK Chaudhary,CK Nandan,Kings XI Punjab

In [94]:
ipl_new.to_csv('IPL_dataset.csv', index=False)

In [95]:
ipl_new.to_json('IPL_dataset.json', orient='records')